export * from './types';
export * from './token-store';
export * from './client';
export type { JoinReadiness, JoinToken } from './endpoints/video';
export type { PatientFile, FileRequest } from './endpoints/files';
export type { SearchResponse, ServiceMatch, EmergencyGuidance } from './endpoints/search';

import * as authApi from './endpoints/auth';
export { authApi };
import * as profileApi from './endpoints/profile';
export { profileApi };
import * as legalApi from './endpoints/legal';
export { legalApi };
import * as consultationsApi from './endpoints/consultations';
export { consultationsApi };
import * as notificationsApi from './endpoints/notifications';
export { notificationsApi };
import * as catalogueApi from './endpoints/catalogue';
export { catalogueApi };
import * as checkinApi from './endpoints/checkin';
export { checkinApi };
import * as carehubApi from './endpoints/careHub';
export { carehubApi };
import * as videoApi from './endpoints/video';
export { videoApi };
import * as filesApi from './endpoints/files';
export { filesApi };
import * as searchApi from './endpoints/search';
export { searchApi };
import * as slotsApi from './endpoints/slots';
export { slotsApi };
import * as paymentsApi from './endpoints/payments';
export { paymentsApi };
import * as intakeApi from './endpoints/intake';
export { intakeApi };

