import React, { useState } from 'react';
import { View, Text, StyleSheet, Linking } from 'react-native';

import { messageFor } from '@coracure/api/errors';

import { colors, radius, spacing } from '../../theme/brand';
import { typeStyles, fontWeight } from '../../theme/typography';
import { Icon } from '../../components/Icon';
import { Screen, Button } from '../../components/ui';
import { ScreenHeader } from '../../components/ScreenHeader';
import { toast } from '../../components/Toast';
import { fetchFileDownloadUrl, usePatientIdentity } from '../../data/patientFiles';
import { SOURCE_LABEL, type PatientDoc } from '../../data/documents';

/**
 * One document: what it is, who shared it, when, and for which consultation.
 *
 * There is still no in-app preview — this build draws no fake page for one —
 * but "Open file" is real: it mints a signed URL per tap (never at list time,
 * or it would start expiring while a doctor scrolls) and hands it to the OS.
 * A local-only document (added during a consultation this session, not yet a
 * real backend file) has no such URL; the fetch fails and says so.
 */
export const DocumentViewerScreen = ({
  doc,
  consultationLabel,
  onBack,
  onOpenAllDocuments,
}: {
  doc: PatientDoc;
  /** "CON-10482 · 15 May 2026" when the file belongs to a consultation. */
  consultationLabel?: string;
  onBack: () => void;
  onOpenAllDocuments: () => void;
}) => {
  const { patient } = usePatientIdentity(doc.patientId);
  const [opening, setOpening] = useState(false);

  const openFile = async () => {
    setOpening(true);
    try {
      const { url } = await fetchFileDownloadUrl(doc.id);
      await Linking.openURL(url);
    } catch (e) {
      toast.show(messageFor(e), 'error');
    } finally {
      setOpening(false);
    }
  };
  const rows: [string, string][] = [
    ['Patient', `${patient?.name ?? '—'} · ${doc.patientId}`],
    ['File', `${doc.fileType} · ${doc.size} · ${doc.pages} page${doc.pages === 1 ? '' : 's'}`],
    ['Shared', `${doc.uploadedBy === 'patient' ? 'Uploaded by the patient' : 'Generated by CoraCure'} · ${doc.uploadedAt}`],
    ['Source', SOURCE_LABEL[doc.source]],
    ['Consultation', consultationLabel ?? 'General medical history'],
  ];

  return (
    <Screen
      testID="document-viewer"
      header={<ScreenHeader onBack={onBack} inline title={doc.title} subtitle={patient?.name} />}
      footer={
        <View style={s.footer}>
          <Button testID="open-file" label="Open file" icon="eye" onPress={openFile} loading={opening} disabled={opening} />
          <Button
            testID="all-documents"
            label={`All of ${patient?.name.split(' ')[0] ?? 'the patient'}'s documents`}
            variant="secondary"
            onPress={onOpenAllDocuments}
          />
        </View>
      }
    >
      <View style={s.page} accessible accessibilityLabel={`Preview of ${doc.title} is not available in this build`}>
        <View style={s.pageHead}>
          <View style={[s.kind, doc.fileType === 'JPG' && s.kindImg]}>
            <Text style={[s.kindText, doc.fileType === 'JPG' && s.kindTextImg]}>{doc.fileType}</Text>
          </View>
          <Text style={s.pageTitle} numberOfLines={2}>
            {doc.title}
          </Text>
        </View>
        {[0.92, 0.84, 0.9, 0.6, 0.88, 0.74, 0.8, 0.5].map((w, i) => (
          <View key={i} style={[s.line, { width: `${w * 100}%` }]} />
        ))}
        <View style={s.unavailable}>
          <Icon name="info" size={15} color={colors.inkMuted} />
          <Text style={s.unavailableText}>Document preview is not available in this demo build.</Text>
        </View>
      </View>

      <Text style={s.summaryLabel}>About this document</Text>
      <Text testID="doc-summary" style={s.summary}>
        {doc.summary}
      </Text>

      <View style={s.card}>
        {rows.map(([k, v], i) => (
          <View key={k} style={[s.row, i < rows.length - 1 && s.rowRule]}>
            <Text style={s.k}>{k}</Text>
            <Text style={s.v}>{v}</Text>
          </View>
        ))}
      </View>

      <View style={s.scope}>
        <Icon name="lock" size={13} color={colors.surfie} />
        <Text style={s.scopeText}>Visible to you through your assigned care relationship.</Text>
      </View>
    </Screen>
  );
};

const s = StyleSheet.create({
  footer: { gap: spacing.sm },
  page: {
    marginHorizontal: spacing.lg,
    padding: spacing.lg,
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.surface.line,
    gap: 8,
  },
  pageHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  kind: { backgroundColor: colors.dangerSoft, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  kindImg: { backgroundColor: colors.successSoft },
  kindText: { ...typeStyles.caption, fontSize: 11, fontWeight: fontWeight.bold, color: colors.danger },
  kindTextImg: { color: colors.surfie },
  pageTitle: { ...typeStyles.cardTitle, color: colors.ink, flexShrink: 1 },
  line: { height: 6, borderRadius: 3, backgroundColor: colors.surface.line },
  unavailable: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing.md },
  unavailableText: { ...typeStyles.caption, color: colors.inkMuted, flex: 1 },

  summaryLabel: { ...typeStyles.label, color: colors.ink, marginHorizontal: spacing.lg, marginTop: spacing.lg },
  summary: { ...typeStyles.body, color: colors.ink, marginHorizontal: spacing.lg, marginTop: 4 },

  card: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.surface.line,
  },
  row: { flexDirection: 'row', gap: spacing.md, paddingVertical: spacing.sm + 2 },
  rowRule: { borderBottomWidth: 1, borderBottomColor: colors.surface.line },
  k: { ...typeStyles.caption, color: colors.inkMuted, width: 100 },
  v: { ...typeStyles.bodySmall, color: colors.ink, flex: 1 },

  scope: { flexDirection: 'row', alignItems: 'center', gap: 6, marginHorizontal: spacing.lg, marginTop: spacing.md },
  scopeText: { ...typeStyles.caption, color: colors.surfie, flex: 1 },
});

export default DocumentViewerScreen;
